# Basic
title: mupu
subtitle: Welcome to visit my blog
description: Android开发笔记
creator: <a href="http://mupu.online">@mupu</a>

url: "http://mupu.online"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: 

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
 #   - {title: Projects, description: My Projects, url: 'https://github.com/mupu-mupu'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: 
    # duoshuo: 
    
# Social
social:
    github: mupu-mupu
    mail: 18814182294@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

# port
port: 2000